Enhance the assignment filter
innoq/seawatch_planner pull request #109
Opened 2020-01-29 14:08 UTC by janmax

* Selecting a position in the mission detail view will give
  a list of all candidate users by availability and skills.
* It is possible to filter by name.
* It is possible to filter by a custom date range.
* It is possible to filter by different positions.
* It is possible to hide/show the filter fields. The selection persists
  across views.
* It is possible to return to the mission page without making a
  selection.
* The currently assigned user (if any) is always displayed regardless
  of the current filter values.
* Remove django-filters package.
* Closes #19.

2020-01-29 14:09 UTC, janmax commented
Ich wollte erstmal ein bisschen ausprobieren, daher hab ich noch keine Tests. Mindestens die oben genannten Dinge würde ich noch abtesten.

2020-01-30 13:38 UTC, hollesse commented
Also erstmal mein Feedback zum Design. Mir gefällt die Filtermaske selbst sehr gut! Sehe jedoch mehrere Dinge die problematisch sein könnten. Wenn ich alle Felder leer mache und auf Filtern drücke, wäre meine Erwartung, dass ich keinen Filter aktiviert habe, es wird jedoch trotzdem nach leeren werten gefiltert. Ich würde erwarten, dass ich dann alle Profile sehe, die approved sind. Wenn ich dann auf Reset to mission parameter klicke passiert jedoch leider nichts. 

Zusätzlich wäre mein Vorschlag, den Knopf cancel and back to Mission als Button in rot zu gestalten. 
Beim Show filter könnte man ggf. ein Font Awesome Trichter Icon nutzen und hier ggf. auch einen Button und keinen Link nutzen.

2020-01-30 14:01 UTC, hollesse requested changes

2020-01-30 14:01 UTC, hollesse commented on missions/tables/candidates.py
>  class CandidatesTable(tables.Table):
Macht es Sinn hier die Table zu erhalten? Ich hatte das Gefühl, dass die Tables nicht gerade sehr flexible sind um in Hinsicht auf mögliche Hinweise ob jemand bereits in dem Zeitraum verplant ist, wäre es sinnvoll die Table hier direkt mit rauszuwerfen.

2020-01-30 14:01 UTC, hollesse commented on missions/tables/candidates.py
> +    id = tables.Column(verbose_name='', orderable=False)
Wofür benötigen wir einen verbose_name wenn der ein empty string ist?

2020-01-30 14:01 UTC, hollesse commented on missions/templates/missions/assignee_form.html
> +            <script>
Es sollte auch einen <noscript> Tag geben, damit die Filter gezeigt werden, falls Javascript nicht verfügbar ist. Ich fände insgesamt eine Lösung besser wo das Filter Interface eher klein ist und dafür jedoch durchgehen da ist.

2020-01-30 14:01 UTC, hollesse commented on seawatch_registration/views/signup.py
> +    username = CharField(widget=HiddenInput(), required=False)
Macht es Sinn den Username dann wirklich als Hiddenfield zu setzen? kann man den nicht einfach das Field herausnehmen?

2020-01-30 14:05 UTC, janmax commented on missions/tables/candidates.py
> +    id = tables.Column(verbose_name='', orderable=False)
Sonst steht über der Spalte fest ID. Wenn ich django-tables rauswerfe, verschwindet das eh.

2020-01-30 14:07 UTC, janmax commented on missions/templates/missions/assignee_form.html
> +            <script>
Stimme ich zu, Bootstrap `form-inline` sieht allerdings so fürchterlich aus, dass es vermutlich nicht anders geht, außer es selbst hinzubiegen. Für die "Backoffice" Ansichten sollten wir aber doch davon ausgehen können, dass Javascript vorhanden ist, oder?

2020-01-30 14:08 UTC, janmax commented on seawatch_registration/views/signup.py
> +    username = CharField(widget=HiddenInput(), required=False)
Dann speichert er das nicht mehr ab, bzw. ich müsste die `save()` überschreiben. Der Input wird ja eh nicht verarbeitet.

2020-01-30 14:09 UTC, janmax commented on missions/tables/candidates.py
>  class CandidatesTable(tables.Table):
Ok, mache ich.

2020-01-30 14:11 UTC, hollesse commented on missions/tables/candidates.py
> +    id = tables.Column(verbose_name='', orderable=False)
stimmt...

2020-01-30 14:12 UTC, hollesse commented on missions/templates/missions/assignee_form.html
> +            <script>
Ich würde prinzipiell davon ausgehen, dass es nicht da ist. nochmal einen noscript Tag einfügen sollte ja nicht viel Arbeit sein.

2020-01-30 14:13 UTC, hollesse commented on missions/templates/missions/assignee_form.html
> +            <script>
Meinst du Inlineforms sind da wirklich so schlimm?

2020-01-30 14:13 UTC, hollesse commented on seawatch_registration/views/signup.py
> +    username = CharField(widget=HiddenInput(), required=False)
ok

2020-01-30 14:16 UTC, janmax commented on seawatch_registration/views/signup.py
> +    username = CharField(widget=HiddenInput(), required=False)
> Also erstmal mein Feedback zum Design. Mir gefällt die Filtermaske selbst sehr gut! Sehe jedoch mehrere Dinge die problematisch sein könnten. Wenn ich alle Felder leer mache und auf Filtern drücke, wäre meine Erwartung, dass ich keinen Filter aktiviert habe, es wird jedoch trotzdem nach leeren werten gefiltert. Ich würde erwarten, dass ich dann alle Profile sehe, die approved sind. 

Das sollte auch so sein, der Bug ist mir beim test schreiben auch gerade aufgefallen.

> Wenn ich dann auf Reset to mission parameter klicke passiert jedoch leider nichts.

Das ist auch gemogelt, das geht nur, wenn man vom `mission_detail` view kommt, da der reset button einfach nur auf die initial values zurücksetzt. Der ist nur Platzhalter für einen Button mit der versprochenen Funktionalität.

> Zusätzlich wäre mein Vorschlag, den Knopf cancel and back to Mission als Button in rot zu gestalten.

Gute Idee, ich finde die `-outline` Option für sowas auch immer nicht schlecht.

> Beim Show filter könnte man ggf. ein Font Awesome Trichter Icon nutzen und hier ggf. auch einen Button und keinen Link nutzen.

Kann ich machen. Ich will jetzt erstmal mit den Tests so weit kommen, dass ich das meiste abdecke, um für den Rest die Tests vorher schreiben zu können.

2020-01-30 14:16 UTC, janmax commented
> Also erstmal mein Feedback zum Design. Mir gefällt die Filtermaske selbst sehr gut! Sehe jedoch mehrere Dinge die problematisch sein könnten. Wenn ich alle Felder leer mache und auf Filtern drücke, wäre meine Erwartung, dass ich keinen Filter aktiviert habe, es wird jedoch trotzdem nach leeren werten gefiltert. Ich würde erwarten, dass ich dann alle Profile sehe, die approved sind. 

Das sollte auch so sein, der Bug ist mir beim test schreiben auch gerade aufgefallen.

> Wenn ich dann auf Reset to mission parameter klicke passiert jedoch leider nichts.

Das ist auch gemogelt, das geht nur, wenn man vom `mission_detail` view kommt, da der reset button einfach nur auf die initial values zurücksetzt. Der ist nur Platzhalter für einen Button mit der versprochenen Funktionalität.

> Zusätzlich wäre mein Vorschlag, den Knopf cancel and back to Mission als Button in rot zu gestalten.

Gute Idee, ich finde die `-outline` Option für sowas auch immer nicht schlecht.

> Beim Show filter könnte man ggf. ein Font Awesome Trichter Icon nutzen und hier ggf. auch einen Button und keinen Link nutzen.

Kann ich machen. Ich will jetzt erstmal mit den Tests so weit kommen, dass ich das meiste abdecke, um für den Rest die Tests vorher schreiben zu können.

2020-01-30 14:18 UTC, hollesse commented
Bezüglich des Cancel Buttons. Bei den Dialogen zum löschen eines Schiffs z.b. haben wir für den Cancel Button auch einen roten Button genommen kannst du dir ja mal anschauen ;)

2020-01-30 15:16 UTC, janmax commented on missions/templates/missions/assignee_form.html
> +            <script>
Die haben keinerlei margins, sind nicht mit der Tabelle aligned, etc. Denke, das muss man teilweise von Hand machen.

2020-01-31 15:56 UTC, janmax commented on missions/templates/missions/assignee_form.html
> +            <script>
Würde ich gerne auf einen anderen Commit verschieben.

2024-11-12 15:27 UTC, closed without merging